version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: motor_busqueda_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: motor_multimodal
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  postgres_data:
  